version: '3.8'

services:
  frontend:
    build: ./imagitalk_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./imagitalk_frontend/.env.local

  backend:
    build: ./imagitalk_backend
    ports:
      - "8000:8000"
    env_file:
      - ./imagitalk_backend/.env